baseurl = "/"
languageCode = "utf-8"
title = "Life with Mimi"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command

[params]
    site_author = "Chulmin Lee"
    site_description = "The blog of Mimi & Chulmin"
    location = "Beautiful place"
    # Link custom assets relative to /static
    avatar = "img/chulmin.png"
    header_background = "img/life_sky2.jpg"
    header_title = "Life with Mimi"
    copyright = "Chulmin Lee"
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "spf13"
    facebook  = ""
    linkedin  = ""
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "patrasche5138"
    gplus     = ""
